### ISSUE TITLE
Melodic release does not export tf dependency

### ISSUE THREAD

**Issue by drjsmith** [ros-gbp/laser_geometry-release#1]
I used `rosinstall_generator` and `wstool` to initialize a catkin workspace for ROS Melodic on Ubuntu 18.04. As of now, the melodic release branch of `laser_geometry` is `release/melodic/laser_geometry/1.6.4-0`.
Compilation was halted by the following error:
```
Errors     << costmap_2d:make /home//***//system_catkin_ws/logs/costmap_2d/build.make.002.log
In file included from /home//***//system_catkin_ws/src/navigation/costmap_2d/include/costmap_2d/obstacle_layer.h:49:0,
                 from /home/***/system_catkin_ws/src/navigation/costmap_2d/plugins/obstacle_layer.cpp:38:
/home/***/system_catkin_ws/src/laser_geometry/include/laser_geometry/laser_geometry.h:40:10: fatal error: tf/tf.h: No such file or directory
 #include <tf/tf.h>
          ^~~~~~~~~
compilation terminated.
In file included from /home/***/system_catkin_ws/src/navigation/costmap_2d/include/costmap_2d/voxel_layer.h:48:0,
                 from /home/***/system_catkin_ws/src/navigation/costmap_2d/plugins/voxel_layer.cpp:38:
/home/***/system_catkin_ws/src/laser_geometry/include/laser_geometry/laser_geometry.h:40:10: fatal error: tf/tf.h: No such file or directory
 #include <tf/tf.h>
          ^~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/layers.dir/plugins/obstacle_layer.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/layers.dir/plugins/voxel_layer.cpp.o] Error 1
make[1]: *** [CMakeFiles/layers.dir/all] Error 2
make: *** [all] Error 2
```
The `tf` package is in the workspace, and `laser_geometry` was able to build without issue. `costmap_2d` is unable to build because it no longer depends directly on `tf` and `laser_geometry` does not export the dependency on `tf`:
```
catkin_package(
  INCLUDE_DIRS include
  LIBRARIES laser_geometry
  DEPENDS Boost Eigen
)
```

I noted that the [CMakelists](https://github.com/ros-perception/laser_geometry/blob/kinetic-devel/CMakeLists.txt) file for the `kinetic-devel` branch of the primary `laser_geometry` repo does export the dependency.

@wjwwood

**Comment by wjwwood** [comment]
@clalancette @jonbinney

**Comment by jonbinney** [comment]
Whoops! i'll take a look at this now

**Comment by jonbinney** [comment]
Yup, fixed in kinetic-devel branch as @drjsmith noted. I haven't done a melodic release since the fix (only noetic). I'll do that now.

**Comment by jonbinney** [comment]
New release created for melodic from the kinetic-devel branch of laser-filters: https://github.com/ros/rosdistro/pull/24181

**Comment by drjsmith** [comment]
Thank you, I think this issue can be closed now.
